name: Release
on:
  release:
    types:
      - created

jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        always-auth: true
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install electron
      run: yarn add electron-forge
    - name: install dependencies
      run: yarn install
    - name: publish
      run: electron-forge publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        always-auth: true
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install electron
      run: yarn add electron-forge
    - name: install dependencies
      run: yarn install
    - name: publish
      run: electron-forge publish

  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        always-auth: true
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install electron
      run: yarn add electron-forge
    - name: install dependencies
      run: yarn install
    - name: publish
      run: electron-forge publish